// 样式与配色表（P2 拆分自 client.tsx）：纯数据 + 派生工具，全部 --dsw-alias-* token 化。
import type { CSSProperties } from 'react'

/** 统一徽标/状态胶囊的基础尺寸：状态框、scope 徽标、转正/✕/卸载/清理 全部对齐。 */
const pillBase: CSSProperties = {
  display: 'inline-flex',
  alignItems: 'center',
  height: 20,
  boxSizing: 'border-box',
  padding: '0 7px',
  borderRadius: 5,
  fontSize: 12,
  fontWeight: 500,
  whiteSpace: 'nowrap',
  lineHeight: 1,
}

/** 日志级别 → 文本颜色（ok=成功 / warn=警告 / err=危险 / 其它中性）。 */
const LOG_COLOR: Record<string, string> = {
  ok: 'var(--dsw-alias-state-success-primary)',
  warn: 'var(--dsw-alias-state-warning-primary)',
  err: 'var(--dsw-alias-state-danger-primary)',
}

export function logStyle(level: 'info' | 'ok' | 'warn' | 'err'): CSSProperties {
  return { ...s.logText, ...(LOG_COLOR[level] ? { color: LOG_COLOR[level] } : {}) }
}

export const s: Record<string, CSSProperties> = {
  root: { display: 'flex', flexDirection: 'column', gap: 12, padding: 16, minHeight: 0 },
  center: { padding: 24, color: 'var(--dsw-alias-label-tertiary)', fontSize: 13, },
  // 顶部三栏导航
  stickyTop: {
    position: 'sticky',
    top: 0,
    zIndex: 40,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    paddingBottom: 4,
    background: 'var(--dsw-alias-bg-layer-0)',
  },
  tabBar: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '4px',
    borderRadius: 10,
    background: 'var(--dsw-alias-bg-layer-1)',
    border: '1px solid var(--dsw-alias-border-l1)',
    boxShadow: 'var(--dsw-shadow-lv1)',
  },
  tabBtn: {
    border: 'none',
    background: 'transparent',
    color: 'var(--dsw-alias-label-secondary)',
    borderRadius: 7,
    padding: '6px 16px',
    cursor: 'pointer',
    fontSize: 13, fontWeight: 500,
    transition: 'background 0.15s ease, color 0.15s ease',
  },
  tabBtnActive: {
    background: 'color-mix(in srgb, var(--dsw-alias-state-business-primary) 14%, transparent)',
    color: 'var(--dsw-alias-state-business-primary)',
  },
  tabClear: {
    marginLeft: 'auto',
    border: '1px solid var(--dsw-alias-border-l2)',
    background: 'transparent',
    color: 'var(--dsw-alias-label-tertiary)',
    borderRadius: 6,
    padding: '4px 10px',
    cursor: 'pointer',
    fontSize: 11,
    flexShrink: 0,
  },
  // 热插拔面板
  hotswapPanel: { display: 'flex', flexDirection: 'column', gap: 12, minHeight: 0, flex: 1 },
  hotswapHead: { display: 'flex', flexDirection: 'column', gap: 4 },
  hotswapTitle: { fontSize: 15, fontWeight: 600, color: 'var(--dsw-alias-label-primary)' },
  hotswapHint: { fontSize: 12, color: 'var(--dsw-alias-label-tertiary)' },
  // 日志区
  logBox: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
    flex: 1,
    borderRadius: 10,
    background: 'var(--dsw-alias-bg-layer-1)',
    border: '1px solid var(--dsw-alias-border-l1)',
    boxShadow: 'var(--dsw-shadow-lv1)',
    overflow: 'hidden',
  },
  logHead: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 12px',
    borderBottom: '1px solid var(--dsw-alias-border-l2)',
  },
  logTitle: { fontSize: 13, fontWeight: 600, color: 'var(--dsw-alias-label-primary)' },
  logCount: { fontSize: 11, color: 'var(--dsw-alias-label-tertiary)' },
  logActions: { marginLeft: 'auto', display: 'flex', gap: 6 },
  ghostBtnSm: {
    border: '1px solid var(--dsw-alias-border-l2)',
    background: 'transparent',
    color: 'var(--dsw-alias-label-secondary)',
    borderRadius: 6,
    height: 28,
    boxSizing: 'border-box',
    padding: '0 12px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    fontSize: 12,
    flexShrink: 0,
  },
  logView: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    minHeight: 0,
    flex: 1,
    overflowY: 'auto',
    padding: '8px 12px',
    fontFamily: 'var(--ds-font-family-code)',
    fontSize: 12,
  },
  logRow: { display: 'flex', gap: 10, lineHeight: '19px' },
  logTime: { flexShrink: 0, color: 'var(--dsw-alias-label-tertiary)' },
  logText: { whiteSpace: 'pre-wrap', wordBreak: 'break-word' },
  logEmpty: { color: 'var(--dsw-alias-label-tertiary)', fontSize: 12, lineHeight: '20px' },
  // 步骤骨架 + 实时跟踪
  stepBox: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    padding: '8px 12px',
    borderBottom: '1px solid var(--dsw-alias-border-l2)',
  },
  stepHead: { display: 'flex', alignItems: 'center', gap: 8 },
  stepTitle: { fontSize: 12, fontWeight: 600, color: 'var(--dsw-alias-label-primary)' },
  stepHint: { fontSize: 11, color: 'var(--dsw-alias-label-tertiary)', marginLeft: 'auto' },
  stepList: { display: 'flex', flexDirection: 'column', gap: 4 },
  stepRow: { display: 'flex', alignItems: 'center', gap: 7, fontSize: 12, lineHeight: '18px' },
  stepIcon: { display: 'inline-flex', width: 14, justifyContent: 'center', fontSize: 12, flexShrink: 0 },
  stepIconRunning: { animation: 'smStepPulse 1.2s ease-in-out infinite' },
  stepLabel: { color: 'var(--dsw-alias-label-primary)', fontWeight: 500 },
  stepRight: { marginLeft: 'auto', display: 'flex', gap: 8, flexShrink: 0 },
    stepMeta: { fontSize: 11, color: 'var(--dsw-alias-label-tertiary)' },
    stepNote: { maxWidth: 200, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  // 诊断占位
  diagnosePanel: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minHeight: 240,
    padding: 24,
    borderRadius: 10,
    background: 'var(--dsw-alias-bg-layer-1)',
    border: '1px solid var(--dsw-alias-border-l1)',
    boxShadow: 'var(--dsw-shadow-lv1)',
    textAlign: 'center',
  },
  diagnoseTitle: { fontSize: 15, fontWeight: 600, color: 'var(--dsw-alias-label-primary)' },
  diagnoseEmpty: { fontSize: 12, color: 'var(--dsw-alias-label-tertiary)', maxWidth: 420 },
  diagFolderBar: { display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: 6 },
  diagFolderLabel: { fontSize: 12, color: 'var(--dsw-alias-label-secondary)', fontWeight: 500, marginRight: 2 },
  diagChip: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    padding: '3px 8px',
    borderRadius: 6,
    fontSize: 12,
    cursor: 'pointer',
    background: 'var(--dsw-alias-bg-layer-2)',
    border: '1px solid var(--dsw-alias-border-l1)',
    color: 'var(--dsw-alias-label-secondary)',
  },
  // 代码规范治理面板
  diagHead: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  diagHeadText: { display: 'flex', flexDirection: 'column', gap: 4, minWidth: 0 },
  diagHint: { fontSize: 12, color: 'var(--dsw-alias-label-tertiary)', maxWidth: 560 },
  diagRunBtn: {
    padding: '6px 14px', fontSize: 13, fontWeight: 600, cursor: 'pointer',
    borderRadius: 6, whiteSpace: 'nowrap',
    color: '#fff',
    background: 'linear-gradient(135deg, #3b82f6, #8b5cf6)',
    border: 'none',
  },
  diagSummaryBar: { display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap', fontSize: 12 },
  diagSummaryText: { color: 'var(--dsw-alias-label-primary)', fontWeight: 600 },
  diagSummaryEll: { display: 'flex', gap: 12 },
  diagList: { display: 'flex', flexDirection: 'column', gap: 10, overflow: 'auto', flex: 1, minHeight: 0 },
  diagCard: {
    display: 'flex', flexDirection: 'column', gap: 8, padding: 12,
    borderRadius: 8, background: 'var(--dsw-alias-bg-layer-1)',
    border: '1px solid var(--dsw-alias-border-l1)',
  },
  diagCardHead: { display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  diagCardName: { fontSize: 13, fontWeight: 700, color: 'var(--dsw-alias-label-primary)', fontFamily: 'monospace' },
  diagCardBadge: { fontSize: 11, fontWeight: 600 },
  diagCardMeta: { fontSize: 11, color: 'var(--dsw-alias-label-tertiary)', marginLeft: 'auto' },
  diagRuleList: { display: 'flex', flexDirection: 'column', gap: 6 },
  diagRuleRow: { display: 'flex', gap: 8, alignItems: 'flex-start' },
  diagRuleMark: { fontSize: 13, fontWeight: 700, lineHeight: '18px', width: 14, flexShrink: 0 },
  diagRuleTitle: { fontSize: 12, fontWeight: 600, color: 'var(--dsw-alias-label-primary)' },
  diagRuleDetail: { fontSize: 12, color: 'var(--dsw-alias-label-secondary)', marginTop: 2 },
  diagEvid: { fontSize: 11, color: 'var(--dsw-alias-label-tertiary)', background: 'var(--dsw-alias-bg-layer-2)', padding: '3px 6px', borderRadius: 4, marginTop: 3, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  kernelBanner: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'nowrap',
    whiteSpace: 'nowrap',
    gap: 16,
    padding: '8px 14px',
    borderRadius: 10,
    background: 'var(--dsw-alias-bg-layer-1)',
    border: '1px solid var(--dsw-alias-border-l1)',
    boxShadow: 'var(--dsw-shadow-lv1)',
  },
  kernelCol: { display: 'flex', flexDirection: 'row', alignItems: 'baseline', gap: 6, minWidth: 0 },
  kernelDot: { color: 'var(--dsw-alias-label-tertiary)', fontSize: 13 },
  kernelTitle: { color: 'var(--dsw-alias-label-secondary)', fontSize: 12, fontWeight: 500, whiteSpace: 'nowrap' },
  kernelVersion: { fontSize: 14, fontWeight: 600, color: 'var(--dsw-alias-label-primary)', whiteSpace: 'nowrap' },
  kernelChannel: {
    fontSize: 12,
    fontWeight: 500,
    color: 'var(--dsw-alias-label-primary)',
    fontFamily: 'var(--ds-font-family-code)',
    whiteSpace: 'nowrap',
  },
  body: { display: 'flex', gap: 14, minHeight: 0, flex: 1, alignItems: 'flex-start' },
  sidebar: {
    width: 196,
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    padding: 8,
    borderRadius: 10,
    background: 'var(--dsw-alias-bg-layer-1)',
    border: '1px solid var(--dsw-alias-border-l1)',
    boxShadow: 'var(--dsw-shadow-lv1)',
    // 文件夹栏跟随顶部固定：右侧插件区滚动时文件夹保持可见，便于继续把插件拖入文件夹。
    position: 'sticky',
    top: 0,
    maxHeight: 'min(52vh, 420px)',
    overflowY: 'auto',
    alignSelf: 'flex-start',
  },
  sidebarTitle: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    color: 'var(--dsw-alias-label-secondary)',
    fontSize: 13, fontWeight: 500,
    padding: '4px 6px 6px',
  },
  iconBtn: {
    border: 'none',
    background: 'transparent',
    color: 'var(--dsw-alias-label-tertiary)',
    fontSize: 13, fontWeight: 500,
    cursor: 'pointer',
    width: 26,
    height: 26,
    borderRadius: 6,
  },
  iconBtnSm: {
    border: 'none',
    background: 'transparent',
    color: 'var(--dsw-alias-label-tertiary)',
    cursor: 'pointer',
    padding: '0 3px',
    fontSize: 12,
  },
  createBox: { display: 'flex', gap: 6, margin: '0 2px 4px' },
  input: {
    flex: 1,
    minWidth: 0,
    fontSize: 12,
    color: 'var(--dsw-alias-label-primary)',
    background: 'transparent',
    border: '1px solid var(--dsw-alias-border-l2)',
    borderRadius: 6,
    padding: '5px 8px',
    outline: 'none',
  },
  primaryBtn: {
    border: 'none',
    background: 'var(--dsw-alias-state-business-primary)',
    color: '#fff',
    borderRadius: 6,
    height: 28,
    boxSizing: 'border-box',
    padding: '0 14px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    fontSize: 12, fontWeight: 500,
    flexShrink: 0,
  },
  folder: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '7px 9px',
    borderRadius: 7,
    cursor: 'pointer',
    color: 'var(--dsw-alias-label-primary)',
    fontSize: 12, fontWeight: 500,
    transition: 'background 0.15s ease',
  },
  folderActive: {
    background: 'color-mix(in srgb, var(--dsw-alias-state-business-primary) 13%, transparent)',
    color: 'var(--dsw-alias-state-business-primary)',
  },
  folderName: { flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  folderActions: { display: 'flex', gap: 2 },
  folderCount: {
    fontSize: 12,
    color: 'var(--dsw-alias-label-secondary)',
    background: 'var(--dsw-alias-bg-module-platform)',
    borderRadius: 999,
    padding: '0 7px',
    flexShrink: 0,
  },
  cards: { flex: 1, display: 'flex', flexDirection: 'column', gap: 10, minWidth: 0, minHeight: 0 },
  cardsHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '6px 2px',
    position: 'sticky',
    top: 0,
    zIndex: 5,
    background: 'color-mix(in srgb, var(--dsw-alias-bg-layer-1) 92%, transparent)',
    backdropFilter: 'blur(4px)',
    borderBottom: '1px solid var(--dsw-alias-border-l1)',
  },
  cardsTitle: { fontSize: 15, fontWeight: 600, color: 'var(--dsw-alias-label-primary)', margin: 0 },
  cardsCount: { color: 'var(--dsw-alias-label-tertiary)', fontSize: 12 },
  // 改造2：拖拽悬停落点高亮（文件夹行）。
  folderOver: {
    outline: '2px solid var(--dsw-alias-state-business-primary)',
    background: 'color-mix(in srgb, var(--dsw-alias-state-business-primary) 18%, transparent)',
  },
  // 改造3：插件搜索框（放行首宽自适应）。
  searchBox: {
    marginLeft: 'auto',
    width: 200,
    fontSize: 12,
    color: 'var(--dsw-alias-label-primary)',
    background: 'var(--dsw-alias-bg-layer-2)',
    border: '1px solid var(--dsw-alias-border-l2)',
    borderRadius: 6,
    padding: '4px 8px',
    outline: 'none',
  },
  tempBar: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '6px 10px',
    borderRadius: 9,
    background: 'color-mix(in srgb, var(--dsw-alias-state-warning-primary) 8%, transparent)',
    border: '1px dashed var(--dsw-alias-border-l2)',
  },
  tempHint: { color: 'var(--dsw-alias-label-tertiary)', fontSize: 11, marginLeft: 'auto', whiteSpace: 'nowrap' },
  tempRow: { display: 'flex', alignItems: 'center', gap: 8, width: '100%' },
  dirCrumbs: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 4,
    fontSize: 12,
    color: 'var(--dsw-alias-label-secondary)',
  },
  dirCrumb: {
    cursor: 'pointer',
    padding: '1px 3px',
    borderRadius: 4,
    color: 'var(--dsw-alias-state-business-primary)',
  },
  dirList: { display: 'flex', flexDirection: 'column', gap: 2, maxHeight: 180, overflowY: 'auto' },
  dirRow: {
    display: 'flex',
    alignItems: 'center',
    padding: '3px 6px',
    borderRadius: 5,
    cursor: 'pointer',
    fontSize: 13,
    border: '1px solid transparent',
  },
  dirName: { wordBreak: 'break-all' },
  ghostBtn: {
    border: '1px solid var(--dsw-alias-border-l2)',
    background: 'transparent',
    color: 'var(--dsw-alias-label-secondary)',
    borderRadius: 6,
    height: 28,
    boxSizing: 'border-box',
    padding: '0 12px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    fontSize: 12,
    flexShrink: 0,
  },
  reloadClientBtn: {
    border: '1px solid var(--dsw-alias-border-l2)',
    background: 'var(--dsw-alias-bg-muted)',
    color: 'var(--dsw-alias-label-primary)',
    borderRadius: 6,
    height: 28,
    boxSizing: 'border-box',
    padding: '0 12px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    fontSize: 12,
    flexShrink: 0,
  },
  preflightSwitch: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 7,
    height: 32,
    boxSizing: 'border-box',
    padding: '0 9px',
    borderRadius: 8,
    border: '1px solid var(--dsw-alias-border-l2)',
    background: 'var(--dsw-alias-bg-muted)',
    cursor: 'pointer',
    flexShrink: 0,
    userSelect: 'none',
  },
  preflightSwitchTrackOn: {
    position: 'relative',
    width: 26,
    height: 14,
    borderRadius: 7,
    boxSizing: 'border-box',
    flexShrink: 0,
    transition: 'background .15s ease',
    background: 'var(--dsw-alias-state-success-primary)',
  },
  preflightSwitchTrackOff: {
    position: 'relative',
    width: 26,
    height: 14,
    borderRadius: 7,
    boxSizing: 'border-box',
    flexShrink: 0,
    transition: 'background .15s ease',
    background: 'var(--dsw-alias-border-l2)',
  },
  preflightSwitchKnobOn: {
    position: 'absolute',
    top: 1,
    left: 13,
    width: 12,
    height: 12,
    borderRadius: 6,
    background: '#fff',
    boxShadow: '0 1px 2px rgba(0,0,0,.25)',
    transition: 'left .15s ease',
  },
  preflightSwitchKnobOff: {
    position: 'absolute',
    top: 1,
    left: 1,
    width: 12,
    height: 12,
    borderRadius: 6,
    background: '#fff',
    boxShadow: '0 1px 2px rgba(0,0,0,.25)',
    transition: 'left .15s ease',
  },
  preflightSwitchLabel: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    lineHeight: 1.1,
    color: 'var(--dsw-alias-label-primary)',
    fontSize: 12,
    whiteSpace: 'nowrap',
  },
  preflightSwitchSub: {
    fontSize: 10,
    color: 'var(--dsw-alias-label-secondary)',
    whiteSpace: 'nowrap',
  },
  // 工具管理「开关」：开机绿 / 关红，无文字（需求3）。与预检开关独立，避免污染既有 preflightSwitch。
  toolSwitchTrackOn: {
    position: 'relative',
    width: 26,
    height: 14,
    borderRadius: 7,
    boxSizing: 'border-box',
    flexShrink: 0,
    transition: 'background .15s ease',
    background: 'var(--dsw-alias-state-success-primary)',
  },
  toolSwitchTrackOff: {
    position: 'relative',
    width: 26,
    height: 14,
    borderRadius: 7,
    boxSizing: 'border-box',
    flexShrink: 0,
    transition: 'background .15s ease',
    background: 'var(--dsw-alias-state-danger-primary)',
  },
  toolSwitchKnobOn: {
    position: 'absolute',
    top: 1,
    left: 13,
    width: 12,
    height: 12,
    borderRadius: 6,
    background: '#fff',
    boxShadow: '0 1px 2px rgba(0,0,0,.25)',
    transition: 'left .15s ease',
  },
  toolSwitchKnobOff: {
    position: 'absolute',
    top: 1,
    left: 1,
    width: 12,
    height: 12,
    borderRadius: 6,
    background: '#fff',
    boxShadow: '0 1px 2px rgba(0,0,0,.25)',
    transition: 'left .15s ease',
  },
  // 工具管理：工具详情展开区（描述 + 参数 schema）。
  toolDetailBox: {
    marginTop: 4,
    padding: '8px 10px',
    borderRadius: 8,
    background: 'var(--dsw-alias-bg-muted)',
    border: '1px solid var(--dsw-alias-border-l2)',
    fontSize: 12,
    lineHeight: 1.5,
    color: 'var(--dsw-alias-label-secondary)',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },
  toolSchemaRow: { display: 'flex', alignItems: 'center', gap: 8, fontSize: 12, padding: '2px 0' },
  toolSearchInput: {
    width: 220,
    boxSizing: 'border-box',
    padding: '6px 10px',
    fontSize: 12,
    borderRadius: 8,
    border: '1px solid var(--dsw-alias-border-l2)',
    background: 'var(--dsw-alias-bg-input)',
    color: 'var(--dsw-alias-label-primary)',
    outline: 'none',
  },
  // 工具管理：插件名内联改名输入框（Enter/blur 提交，Esc 取消）。
  toolAliasInput: {
    width: 160,
    boxSizing: 'border-box',
    padding: '3px 8px',
    fontSize: 13, fontWeight: 600,
    borderRadius: 6,
    border: '1px solid var(--dsw-alias-state-business-primary)',
    background: 'var(--dsw-alias-bg-input)',
    color: 'var(--dsw-alias-label-primary)',
    outline: 'none',
  },
  // 工具管理：分区标题（插件分组 / 工具组卡片）。
  toolSectionHeader: {
    display: 'flex',
    alignItems: 'baseline',
    gap: 8,
    marginTop: 4,
    paddingBottom: 2,
    borderBottom: '1px solid var(--dsw-alias-border-l2)',
  },
  toolSectionTitle: { fontSize: 13, fontWeight: 700, color: 'var(--dsw-alias-label-primary)' },
  toolSectionCount: { fontSize: 11, color: 'var(--dsw-alias-label-tertiary)' },
  // 工具管理：新建自定义工具组卡行。
  toolCatCreateRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '6px 0',
  },
  toolCatDraftInput: {
    width: 200,
    boxSizing: 'border-box',
    padding: '6px 10px',
    fontSize: 12,
    borderRadius: 8,
    border: '1px dashed var(--dsw-alias-border-l2)',
    background: 'var(--dsw-alias-bg-input)',
    color: 'var(--dsw-alias-label-primary)',
    outline: 'none',
  },
  // 工具管理：卡片头部操作按钮（自定义卡改名/删除、未分组说明）。
  toolCatAction: {
    border: '1px solid var(--dsw-alias-border-l2)',
    background: 'transparent',
    color: 'var(--dsw-alias-label-tertiary)',
    borderRadius: 5,
    padding: '2px 6px',
    cursor: 'pointer',
    fontSize: 11,
    lineHeight: 1.4,
  },
  toolCatActionDanger: {
    border: '1px solid var(--dsw-alias-state-danger-primary)',
    background: 'transparent',
    color: 'var(--dsw-alias-state-danger-primary)',
    borderRadius: 5,
    padding: '2px 6px',
    cursor: 'pointer',
    fontSize: 11,
    lineHeight: 1.4,
  },
  headRight: { display: 'flex', alignItems: 'center', gap: 6, minWidth: 0 },
  noteChip: {
    ...pillBase,
    fontFamily: 'var(--ds-font-family-code)',
    color: 'var(--dsw-alias-state-warning-primary)',
    background: 'color-mix(in srgb, var(--dsw-alias-state-warning-primary) 14%, transparent)',
    border: '1px dashed var(--dsw-alias-state-warning-primary)',
  },
  statusBox: {
    ...pillBase,
    fontFamily: 'var(--ds-font-family-code)',
    gap: 6,
    background: 'var(--dsw-alias-bg-module-platform)',
    border: '1px solid transparent',
  },
  statusBoxClick: {
    ...pillBase,
    fontFamily: 'var(--ds-font-family-code)',
    gap: 6,
    background: 'var(--dsw-alias-bg-module-platform)',
    border: '1px solid var(--dsw-alias-border-l2)',
    cursor: 'pointer',
    transition: 'border-color 0.12s ease, box-shadow 0.12s ease',
  },
  statusBoxOrphan: {
    borderColor: 'var(--dsw-alias-state-danger-primary)',
  },
  statusDot: { width: 8, height: 8, borderRadius: 999, flexShrink: 0, display: 'inline-block' },
  statusTextNeutral: { color: 'var(--dsw-alias-label-secondary)' },
  statusSrc: { opacity: 0.6, whiteSpace: 'nowrap' },
  statusSrcOrphan: { color: 'var(--dsw-alias-state-danger-primary)', opacity: 1 },
  tempRemoveBtn: {
    ...pillBase,
    color: 'var(--dsw-alias-state-danger-primary)',
    background: 'color-mix(in srgb, var(--dsw-alias-state-danger-primary) 8%, transparent)',
    border: '1px solid color-mix(in srgb, var(--dsw-alias-state-danger-primary) 40%, transparent)',
    cursor: 'pointer',
  },
  promoteBtn: {
    ...pillBase,
    border: '1px solid var(--dsw-alias-state-warning-primary)',
    background: 'color-mix(in srgb, var(--dsw-alias-state-warning-primary) 14%, transparent)',
    color: 'var(--dsw-alias-state-warning-primary)',
    cursor: 'pointer',
  },
  flash: {
    padding: '8px 12px',
    borderRadius: 7,
    background: 'color-mix(in srgb, var(--dsw-alias-state-success-primary) 14%, transparent)',
    color: 'var(--dsw-alias-state-success-primary)',
    fontSize: 12,
  },
  empty: { padding: 32, textAlign: 'center', color: 'var(--dsw-alias-label-tertiary)', fontSize: 13, },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(236px, 1fr))',
    gap: 12,
    minHeight: 0,
  },
  card: {
    display: 'flex',
    flexDirection: 'column',
    gap: 7,
    padding: 12,
    borderRadius: 10,
    background: 'var(--dsw-alias-bg-layer-1)',
    border: '1px solid var(--dsw-alias-border-l1)',
    boxShadow: 'var(--dsw-shadow-lv1)',
    cursor: 'grab',
    position: 'relative',
  },
  // 拖拽排序插入指示条：悬停时在目标卡片左/右边缘显示 2px 竖线（改造：放宽精确落点）。
  dropLine: {
    position: 'absolute',
    top: 4,
    bottom: 4,
    width: 2,
    zIndex: 3,
    borderRadius: 2,
    background: 'var(--dsw-alias-state-business-primary)',
  },
  // 改造2：拖拽悬停落点高亮（插件卡片）。
  cardOver: {
    outline: '2px solid var(--dsw-alias-state-business-primary)',
    boxShadow: 'var(--dsw-shadow-lv2)',
  },
  cardHead: { display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
  badge: {
    ...pillBase,
    fontFamily: 'var(--ds-font-family-code)',
    color: 'var(--dsw-alias-state-business-primary)',
    background: 'color-mix(in srgb, var(--dsw-alias-state-business-primary) 12%, transparent)',
  },
  badgeThird: {
    ...pillBase,
    fontFamily: 'var(--ds-font-family-code)',
    color: 'var(--dsw-alias-label-secondary)',
    background: 'var(--dsw-alias-bg-module-platform)',
  },
  badgeShell: {
    ...pillBase,
    fontFamily: 'var(--ds-font-family-code)',
    color: 'var(--dsw-alias-tertiary-color, var(--dsw-alias-state-warning-primary))',
    background: 'color-mix(in srgb, var(--dsw-alias-state-warning-primary) 12%, transparent)',
  },
  cardTitleRow: { display: 'flex', alignItems: 'center', gap: 6, minWidth: 0 },
  cardName: {
    flex: 1,
    minWidth: 0,
    fontSize: 13, fontWeight: 500,
    color: 'var(--dsw-alias-label-primary)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    lineHeight: '20px',
  },
  cardVersion: {
    font: 'var(--ds-font-family-code)',
    fontSize: 11,
    color: 'var(--dsw-alias-label-tertiary)',
  },
  cardMeta: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    marginTop: 2,
    paddingTop: 8,
    borderTop: '1px solid var(--dsw-alias-border-l2)',
  },
  depsCount: {
    flexShrink: 0,
    fontSize: 11,
    fontWeight: 600,
    whiteSpace: 'nowrap',
    cursor: 'pointer',
    fontFamily: 'var(--ds-font-family-code)',
    userSelect: 'none',
  },
  depsBox: {
    display: 'flex',
    flexDirection: 'column',
    gap: 5,
    padding: '8px 10px',
    borderRadius: 7,
    background: 'var(--dsw-alias-bg-module-platform)',
    border: '1px solid var(--dsw-alias-border-l2)',
  },
  depsTitle: { fontSize: 11, fontWeight: 600, color: 'var(--dsw-alias-label-secondary)' },
  depsEmpty: { fontSize: 11, color: 'var(--dsw-alias-label-tertiary)', lineHeight: '15px' },
  depsList: { display: 'flex', flexDirection: 'column', gap: 3, maxHeight: 300, overflowY: 'auto' },
  depsItem: {
    fontSize: 11,
    color: 'var(--dsw-alias-label-secondary)',
    fontFamily: 'var(--ds-font-family-code)',
    whiteSpace: 'normal',
    wordBreak: 'break-all',
    lineHeight: '15px',
  },
  uninstallBtn: {
    ...pillBase,
    border: '1px solid color-mix(in srgb, var(--dsw-alias-state-danger-primary) 45%, transparent)',
    background: 'color-mix(in srgb, var(--dsw-alias-state-danger-primary) 14%, transparent)',
    color: 'var(--dsw-alias-state-danger-primary)',
    cursor: 'pointer',
  },
  cardDesc: {
    fontSize: 12,
    color: 'var(--dsw-alias-label-secondary)',
    minHeight: 34,
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
    lineHeight: '17px',
  },
  cardDescMuted: {
    fontSize: 12,
    color: 'var(--dsw-alias-label-tertiary)',
    minHeight: 34,
    lineHeight: '17px',
  },
  noteBox: { marginTop: 'auto', paddingTop: 7, borderTop: '1px solid var(--dsw-alias-border-l2)' },
  noteText: {
    width: '100%',
    textAlign: 'left',
    border: 'none',
    background: 'transparent',
    color: 'var(--dsw-alias-label-secondary)',
    fontSize: 12,
    cursor: 'text',
    padding: 0,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },
  noteTextarea: {
    width: '100%',
    resize: 'none',
    fontSize: 12,
    color: 'var(--dsw-alias-label-primary)',
    background: 'transparent',
    border: '1px solid var(--dsw-alias-border-l2)',
    borderRadius: 6,
    padding: '6px 8px',
    outline: 'none',
  },
  switchLabel: { display: 'inline-flex', alignItems: 'center', cursor: 'pointer' },
  checkboxHidden: { opacity: 0, position: 'absolute', width: 0, height: 0, margin: 0, pointerEvents: 'none' },
  switch: {
    width: 40,
    height: 20,
    borderRadius: 999,
    position: 'relative',
    display: 'inline-block',
    background: 'var(--dsw-alias-bg-layer-3)',
    boxShadow: 'inset 0 0 0 1px var(--dsw-alias-border-l1)',
    transition: 'background 0.2s ease',
  },
  knob: {
    position: 'absolute',
    top: 2,
    left: 2,
    width: 16,
    height: 16,
    borderRadius: 999,
    background: '#fff',
    boxShadow: 'var(--dsw-shadow-lv1)',
    transition: 'transform 0.2s ease',
  },
  // 改造1：目录选择独立弹窗。
  modalMask: {
    position: 'fixed',
    inset: 0,
    zIndex: 1000,
    background: 'rgba(0,0,0,.4)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalPanel: {
    width: 520,
    maxWidth: '92vw',
    maxHeight: '80vh',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    padding: 16,
    borderRadius: 12,
    background: 'var(--dsw-alias-bg-layer-2)',
    border: '1px solid var(--dsw-alias-border-l1)',
    boxShadow: 'var(--dsw-shadow-lv2)',
  },
  modalHead: { display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
  modalTitle: { fontSize: 14, fontWeight: 600, color: 'var(--dsw-alias-label-primary)' },
  modalBody: { fontSize: 13, color: 'var(--dsw-alias-label-secondary)', lineHeight: 1.6, whiteSpace: 'pre-wrap' },
  modalFooter: { display: 'flex', justifyContent: 'flex-end', gap: 8, marginTop: 8 },
  checkboxRow: { display: 'flex', alignItems: 'center', gap: 8, marginTop: 8 },
  checkbox: { width: 14, height: 14, accentColor: 'var(--dsw-color-primary)', flexShrink: 0 },
  checkboxLabel: { fontSize: 13, color: 'var(--dsw-alias-label-secondary)', lineHeight: 1.4 },
  dangerBtn: { background: 'var(--dsw-alias-state-danger-primary, #e74c3c)' },
}
